version: '0.1'

services:
  tinyurl:
    container_name: tinyurlservice
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    expose: 
      - 8080
    depends_on:
      - db
  db:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db_Dockerfile
    container_name: tinyurldb
    environment:
      MYSQL_DATABASE: url
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    expose:
      - 3306
    ports:
      - "3306:3306"
  redis:
    platform: linux/x86_64
    image: redis:7.2.2
    expose:
      - 6379
    ports:
      - "6379:6379"
    depends_on:
      - db
